name: Check and test

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  check-and-test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check format
        run: uvx ruff format --check

      - name: Check import order
        run: uvx ruff check

      - name: Static type check
        run: uv run mypy

      - name: Run tests
        run: uv run pytest tests
